-- JobAgent 2.0.0-alpha.1 initial schema
-- FROZEN / IMMUTABLE after alpha.1 stabilization.
-- Do not edit this file to evolve the schema. Add 002_*.sql, 003_*.sql, …
-- Jobs are shared. Candidate-specific state lives only on candidate_job_matches.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT DEFAULT '',
    url TEXT NOT NULL,
    description TEXT DEFAULT '',
    source TEXT DEFAULT '',
    salary_raw TEXT DEFAULT '',
    posted_at TEXT DEFAULT '',
    found_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_url ON jobs(url);
CREATE INDEX IF NOT EXISTS idx_jobs_found_at ON jobs(found_at DESC);
CREATE INDEX IF NOT EXISTS idx_jobs_source ON jobs(source);
CREATE INDEX IF NOT EXISTS idx_jobs_company ON jobs(company);

CREATE TABLE IF NOT EXISTS candidates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    location TEXT DEFAULT '',
    linkedin TEXT DEFAULT '',
    github TEXT DEFAULT '',
    resume_text TEXT DEFAULT '',
    resume_file TEXT DEFAULT '',
    min_match_score INTEGER DEFAULT 65,
    salary_min INTEGER DEFAULT 0,
    salary_max INTEGER DEFAULT 0,
    keywords_text TEXT DEFAULT '',
    hej_category_ids TEXT DEFAULT '',
    commute_auto_apply_minutes INTEGER DEFAULT 30,
    commute_review_minutes INTEGER DEFAULT 90,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS candidate_titles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    candidate_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_candidate_titles_cid ON candidate_titles(candidate_id);

CREATE TABLE IF NOT EXISTS candidate_employers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    candidate_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    source_type TEXT DEFAULT 'workday',
    careers_url TEXT DEFAULT '',
    workday_url TEXT DEFAULT '',
    greenhouse_slug TEXT DEFAULT '',
    lever_slug TEXT DEFAULT '',
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_candidate_employers_cid ON candidate_employers(candidate_id);

CREATE TABLE IF NOT EXISTS candidate_job_matches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    candidate_id INTEGER NOT NULL,
    job_id TEXT NOT NULL,
    score INTEGER DEFAULT NULL,
    score_reason TEXT DEFAULT NULL,
    status TEXT NOT NULL DEFAULT 'new',
    status_reason TEXT DEFAULT '',
    work_type TEXT DEFAULT NULL,
    commute_minutes INTEGER DEFAULT NULL,
    commute_note TEXT DEFAULT NULL,
    commute_result TEXT DEFAULT NULL,
    auto_apply_eligible INTEGER NOT NULL DEFAULT 0,
    review_status TEXT NOT NULL DEFAULT 'pending',
    resume_path TEXT DEFAULT NULL,
    cover_path TEXT DEFAULT NULL,
    notified INTEGER NOT NULL DEFAULT 0,
    notified_at TEXT DEFAULT NULL,
    application_state TEXT NOT NULL DEFAULT 'none',
    applied_at TEXT DEFAULT NULL,
    application_result TEXT DEFAULT NULL,
    application_error TEXT DEFAULT NULL,
    matched_at TEXT NOT NULL,
    status_updated_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE,
    UNIQUE (candidate_id, job_id)
);

CREATE INDEX IF NOT EXISTS idx_cjm_candidate_status
    ON candidate_job_matches (candidate_id, status);
CREATE INDEX IF NOT EXISTS idx_cjm_score
    ON candidate_job_matches (candidate_id, score);
CREATE INDEX IF NOT EXISTS idx_cjm_job ON candidate_job_matches (job_id);
CREATE INDEX IF NOT EXISTS idx_cjm_matched_at ON candidate_job_matches (matched_at);

CREATE TABLE IF NOT EXISTS run_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run_at TEXT NOT NULL,
    source TEXT DEFAULT '',
    found INTEGER DEFAULT 0,
    new INTEGER DEFAULT 0,
    applied INTEGER DEFAULT 0,
    flagged INTEGER DEFAULT 0,
    errors TEXT DEFAULT '',
    dry_run INTEGER NOT NULL DEFAULT 1,
    candidate_id INTEGER DEFAULT NULL,
    summary TEXT DEFAULT '',
    FOREIGN KEY (candidate_id) REFERENCES candidates(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_run_history_run_at ON run_history(run_at DESC);

CREATE TABLE IF NOT EXISTS import_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    started_at TEXT NOT NULL,
    finished_at TEXT NOT NULL,
    source_path TEXT NOT NULL,
    report_json TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT
);
